# Generated by Django 6.0.3 on 2026-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono del courier'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_proof',
            field=models.ImageField(blank=True, null=True, upload_to='orders/proofs/', verbose_name='Comprobante de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de guía'),
        ),
    ]
