# Generated by Django 6.0.3 on 2026-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_courier_contact_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagado / Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('completed', 'Completado')], default='pending', max_length=20),
        ),
    ]
