# Generated by Django 6.0.3 on 2026-03-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_buyer_confirmed_info_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagado / Procesando'), ('shipped', 'Enviado (Por confirmar)'), ('info_rejected', 'Info. Rechazada por Comprador'), ('delivered', 'Entregado / Finalizado')], default='pending', max_length=20),
        ),
    ]
